### ISSUE TITLE
Missing references to secnodary color

### ISSUE THREAD

**Issue by mariocalin** [stisla/stisla#108]
Classes _badge-secondary_ and _card-secondary_ don't apply the **secondary** color set in __variables.scss_ files. 

```scss
/* _badge.scss file */
  &.badge-secondary {
    background-color: color(fontdark);
  }

/* _card-scss file */
.card-secondary {
    border-top: 2px solid color(fontdark);
  }
```

Shouldn't they reference to the _secondary_ instead of _fontdark_?
